# Generated by Django 5.1.1 on 2024-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Revenues',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], default='', max_length=7),
        ),
    ]
