# Generated by Django 5.1.1 on 2024-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_expenses_delete_revenues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], max_length=7),
        ),
    ]
