# Generated by Django 5.1.1 on 2024-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icone',
            field=models.CharField(max_length=100),
        ),
    ]
